# Generated by Django 2.0.6 on 2018-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('stars_text', models.CharField(max_length=10)),
                ('release_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
